### ISSUE TITLE
Implement Basic CI Workflow

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#47]
## Overview
Implement the foundational CI workflow for the gRPC Client Generator monorepo.

## Acceptance Criteria
- [ ] Create .github/workflows/ci.yml
- [ ] Set up Node.js 20 with npm caching
- [ ] Install jq dependency for preflight
- [ ] Run lab preflight command
- [ ] Configure branch protection rules
- [ ] Ensure CI runs on push to main and PRs

## Implementation Details
```yaml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '20'
  
jobs:
  quick-check:
    name: Quick Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install jq
        run: |
          if \! command -v jq &>/dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          fi
      
      - name: Install root dependencies
        run: npm ci --workspace-root
        
      - name: Run preflight checks
        run: ./cli/lab preflight
```

## Definition of Done
- [ ] CI workflow file created and committed
- [ ] Workflow successfully runs on PR
- [ ] Branch protection configured to require CI pass
- [ ] Documentation updated with CI status badge

## Related to
- Epic: #46 (CI GitHub Actions Setup)
