### ISSUE TITLE
Add Change Detection and Matrix Builds for CI

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#48]
## Overview
Enhance CI workflow with intelligent change detection and parallel matrix builds for improved performance.

## Acceptance Criteria
- [ ] Implement path-based filtering with dorny/paths-filter
- [ ] Create matrix strategies for different package types
- [ ] Add conditional job execution based on changes
- [ ] Optimize for monorepo structure

### Change Detection Job
```yaml
detect-changes:
  name: Detect Changes
  runs-on: ubuntu-latest
  outputs:
    packages: ${{ steps.filter.outputs.changes }}
    apis: ${{ steps.filter.outputs.apis }}
    libs: ${{ steps.filter.outputs.libs }}
    services: ${{ steps.filter.outputs.services }}
  steps:
    - uses: actions/checkout@v4
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          apis:
            - 'apis/**'
            - 'protos/**'
          libs:
            - 'libs/**'
          services:
            - 'services/**'
          product-api:
            - 'apis/product-api/**'
            - 'protos/product.proto'
          user-api:
            - 'apis/user-api/**'
            - 'protos/user.proto'
          grpc-client-generator:
            - 'libs/grpc-client-generator/**'
          example-service:
            - 'services/example-service/**'
```

### Matrix Build Jobs
- Separate jobs for libraries, APIs, and services
- Parallel execution within each category
- Skip unchanged packages

## Benefits
- Reduces CI time by 60-70% for typical PRs
- Only runs necessary tests
- Maintains comprehensive coverage

## Definition of Done
- [ ] Change detection implemented and tested
- [ ] Matrix builds working for all package types
- [ ] Conditional execution verified
- [ ] Performance metrics documented

## Related to
- Epic: #46 (CI GitHub Actions Setup)
- Depends on: #47 (Phase 1 Basic CI)
