### ISSUE TITLE
Implement Caching Strategy for CI Pipeline

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#49]
## Overview
Add comprehensive caching to optimize CI performance and reduce build times.

## Acceptance Criteria
- [ ] Cache npm dependencies efficiently
- [ ] Cache build artifacts where appropriate
- [ ] Cache proto generation outputs
- [ ] Implement cache invalidation strategy

### NPM Caching Strategy
```yaml
- name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: ${{ env.NODE_VERSION }}
    cache: 'npm'
    cache-dependency-path: |
      package-lock.json
      apis/*/package-lock.json
      libs/*/package-lock.json
      services/*/package-lock.json
```

### Advanced Caching
```yaml
- name: Cache npm cache directory
  uses: actions/cache@v4
  with:
    path: ~/.npm
    key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-npm-cache-

- name: Cache proto outputs
  uses: actions/cache@v4
  with:
    path: |
      apis/*/src/generated
    key: ${{ runner.os }}-proto-${{ hashFiles('protos/**/*.proto') }}
```

## Cache Keys Strategy
- Use content-based hashing for accuracy
- Implement restore-keys for partial matches
- Version cache keys when needed

## Expected Improvements
- Cold cache: 5-7 minutes → 3-4 minutes
- Warm cache: 3-4 minutes → 1-2 minutes
- Proto generation: Skip if unchanged

## Definition of Done
- [ ] All caching strategies implemented
- [ ] Cache hit rates > 90%
- [ ] Performance improvements measured
- [ ] Documentation updated

## Related to
- Epic: #46 (CI GitHub Actions Setup)
- Depends on: #48 (Phase 2 Matrix Builds)
