### ISSUE TITLE
Add Component-Specific Test Jobs

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#50]
## Overview
Implement specialized test jobs for different component types (APIs, libraries, services) with appropriate tooling and checks.

## Acceptance Criteria
- [ ] Library test job with full verification suite
- [ ] API test job with proto generation and E2E tests
- [ ] Service test job with build validation
- [ ] Proper error handling and reporting

### Library Testing Job
```yaml
test-libraries:
  name: Test Libraries
  needs: [quick-check, detect-changes]
  if: needs.detect-changes.outputs.libs == 'true'
  runs-on: ubuntu-latest
  timeout-minutes: 15
  strategy:
    matrix:
      package: [grpc-client-generator]
  steps:
    # Full verification: lint, type-check, test, build
```

### API Testing Job
Special requirements:
- Install protoc via arduino/setup-protoc@v3
- Run proto generation before tests
- Execute E2E tests with test script

### Service Testing Job
- Conditional build and test
- Support for future service additions

## Testing Matrix
| Component Type | Checks | Special Requirements |
|---|---|---|
| Libraries | lint, type-check, test, build, verify | None |
| APIs | generate, lint, type-check, build, test, test:e2e | protoc installation |
| Services | build, test (if present) | None |

## Definition of Done
- [ ] All component types have dedicated test jobs
- [ ] Jobs run only when relevant files change
- [ ] Clear error messages on failures
- [ ] Logs available for debugging

## Related to
- Epic: #46 (CI GitHub Actions Setup)
- Depends on: #48 (Phase 2 Matrix Builds)
