### ISSUE TITLE
Implement Integration Testing Suite

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#51]
## Overview
Add integration testing capabilities to validate cross-package dependencies and ensure components work together correctly.

## Acceptance Criteria
- [ ] Set up Verdaccio for local registry testing
- [ ] Implement cross-package dependency tests
- [ ] Test library publishing workflow
- [ ] Validate consumer packages can use published libraries

### Integration Test Job
```yaml
integration-tests:
  name: Integration Tests
  needs: [quick-check, detect-changes]
  if: |
    needs.detect-changes.outputs.apis == 'true' || 
    needs.detect-changes.outputs.libs == 'true' ||
    needs.detect-changes.outputs.services == 'true'
  runs-on: ubuntu-latest
  timeout-minutes: 20
  steps:
    - name: Start local registry
      run: docker run -d -p 4873:4873 --name verdaccio verdaccio/verdaccio
    
    - name: Setup lab environment
      run: ./cli/lab setup
    
    - name: Publish libraries
      run: ./cli/lab publish grpc-client-generator
    
    - name: Run integration tests
      run: |
        # Add cross-package test commands
```

## Test Scenarios
1. Library publishing to local registry
2. API using published library
3. Service consuming API clients
4. Version compatibility checks

## Docker Requirements
- Verdaccio container for npm registry
- Network setup for service communication
- Clean teardown after tests

## Definition of Done
- [ ] Integration test suite implemented
- [ ] All cross-package scenarios covered
- [ ] Docker containers properly managed
- [ ] Clear failure diagnostics

## Related to
- Epic: #46 (CI GitHub Actions Setup)
- Depends on: #50 (Component Test Jobs)
