### ISSUE TITLE
Add Security Scanning Workflows

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#52]
## Overview
Implement security scanning workflows to identify vulnerabilities and maintain dependency health.

## Acceptance Criteria
- [ ] Dependency vulnerability scanning (PR-level via dependency-review action)
- [x] CodeQL analysis for code security (already implemented for JavaScript)
- [ ] CodeQL analysis for TypeScript
- [ ] npm audit integration in CI pipeline
- [ ] Automated security alerts (already handled by Renovate)

### Dependency Review Workflow
```yaml
name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
```

### CodeQL Analysis Enhancement
Update existing `.github/workflows/codeql.yml` to include TypeScript:
```yaml
strategy:
  matrix:
    language: ['javascript', 'typescript']
```

### npm audit Integration
Add to existing CI workflow:
```yaml
- name: Security audit
  run: npm audit --audit-level=moderate
```

## Security Checks
- Known vulnerability detection
- License compliance  
- Dependency freshness (handled by Renovate)
- Code pattern analysis

## Definition of Done
- [ ] Dependency review workflow created
- [ ] CodeQL enhanced for TypeScript
- [ ] npm audit integrated in CI
- [ ] Security scans running on schedule
- [ ] Alerts configured for team

## Related to
- Epic: #46 (CI GitHub Actions Setup)

## Notes
- Dependency updates and vulnerability alerts already handled by Renovate (.github/renovate.json)
- No need for Dependabot configuration
