### ISSUE TITLE
Configure Branch Protection and Status Checks

### ISSUE THREAD

**Issue by frgul006** [frgul006/grpc-client-generator#53]
## Overview
Set up GitHub branch protection rules to enforce CI requirements and maintain code quality.

## Acceptance Criteria
- [ ] Configure main branch protection
- [ ] Require CI status checks to pass
- [ ] Set up PR review requirements
- [ ] Document protection rules

### Required Status Checks
- ci-status (aggregated check from CI workflow)
- codeql-analysis (security scanning)

### Protection Rules
- [ ] Require pull request reviews (1 approval)
- [ ] Dismiss stale PR approvals on new commits
- [ ] Require status checks before merging
- [ ] Require branches to be up to date
- [ ] Include administrators in restrictions
- [ ] Restrict force pushes

### CI Status Aggregation
```yaml
ci-status:
  name: CI Status
  runs-on: ubuntu-latest
  needs: [quick-check, test-libraries, test-apis, test-services]
  if: always()
  steps:
    - name: Check CI Status
      run: |
        # Aggregate all job results
        # Exit with failure if any required job failed
```

## Additional Protections
- No direct pushes to main
- All changes via PR
- Automated dependency updates require approval
- Tag protection for releases

## Definition of Done
- [ ] Branch protection rules configured
- [ ] Status checks enforced
- [ ] Team notified of changes
- [ ] Documentation in README

## Related to
- Epic: #46 (CI GitHub Actions Setup)
- Blocks: All other CI tasks
